// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _GeneralBirthdayProblem_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// simulateC
float simulateC(int k, int roomSize, int replicate);
RcppExport SEXP _GeneralBirthdayProblem_simulateC(SEXP kSEXP, SEXP roomSizeSEXP, SEXP replicateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type roomSize(roomSizeSEXP);
    Rcpp::traits::input_parameter< int >::type replicate(replicateSEXP);
    rcpp_result_gen = Rcpp::wrap(simulateC(k, roomSize, replicate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GeneralBirthdayProblem_rcpp_hello_world", (DL_FUNC) &_GeneralBirthdayProblem_rcpp_hello_world, 0},
    {"_GeneralBirthdayProblem_simulateC", (DL_FUNC) &_GeneralBirthdayProblem_simulateC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GeneralBirthdayProblem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
