# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_GeneralBirthdayProblem_rcpp_hello_world`)
}

simulateC <- function(k, room, replicate) {
    .Call(`_GeneralBirthdayProblem_simulateC`, k, room, replicate)
}

